### ISSUE TITLE
pnat disable fails

### ISSUE THREAD

**Issue by totalrisp** [grdkly/pi-robot-rc-android-bluetooth#1]
If the guide is followed and pnat is diablled in /etc/bluetooth/main.conf, then when one looks at the status of bluetooth.service:
`bluetoothd[507]: Unknown key DisablePlugins in ma...f`

So apparently that workaround from the Debian bug report does not work.

**Comment by grdkly** [comment]
Thanks for your issue report. You are correct, that key is not recognised by the current version of bluez (5.23), and the underlying Debian [bug](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=690749) appears to have been resolved in an earlier release.

README.md updated to remove the incorrect instruction.
